# xinghuo-local/docker-compose.yml

services:
  # 这是我们的“前台总机”服务
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      # 关键修正: 直接覆盖主配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - xinghuo-local
    networks:
      - shared_network

  # 这是我们的“工人”服务
  xinghuo-local:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # 工人不直接对外暴露端口
    env_file:
      - .env
    environment:
      # 您可以按需设置代理
      # - HTTP_PROXY=http://host.docker.internal:7890
      # - HTTPS_PROXY=http://host.docker.internal:7890
      - NO_PROXY=localhost,127.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge